2016-04-10 22:39:44.303 [info] <0.7.0> Application lager started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:44.304 [info] <0.7.0> Application poolgirl started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:44.329 [info] <0.460.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.460.0>
2016-04-10 22:39:44.351 [info] <0.528.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.528.0>
2016-04-10 22:39:44.845 [info] <0.638.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.638.0>
2016-04-10 22:39:45.224 [warning] <0.6.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:45.350 [error] <0.633.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.650.0> exit with reason killed in context child_terminated
2016-04-10 22:39:45.121 [info] <0.7.0> Application lager started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:45.121 [info] <0.7.0> Application poolgirl started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:45.198 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.99.0>
2016-04-10 22:39:45.213 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:45.351 [error] <0.98.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:39:45.351 [error] <0.633.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.650.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:45.351 [error] <0.98.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:45.352 [error] <0.629.0> CRASH REPORT Process <0.629.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:45.352 [error] <0.92.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.94.0> exit with reason killed in context child_terminated
2016-04-10 22:39:45.352 [error] <0.92.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.94.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:45.352 [error] <0.96.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:39:45.352 [error] <0.96.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:45.352 [error] <0.95.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:39:45.352 [error] <0.95.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:45.352 [error] <0.114.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:39:45.352 [error] <0.114.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:45.352 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:45.410 [info] <0.765.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.765.0>
2016-04-10 22:39:45.415 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:45.828 [error] <0.759.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'...

2016-04-10 22:39:45.354 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:39:45.430 [info] <0.216.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.216.0>
2016-04-10 22:39:45.878 [info] <0.369.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.369.0>
2016-04-10 22:39:45.861 [info] <0.893.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.893.0>
2016-04-10 22:39:46.164 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:46.165 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:46.689 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:39:46.723 [info] <0.991.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.991.0>
2016-04-10 22:39:47.480 [error] <0.986.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1006.0> exit with reason killed in context child_terminated
2016-04-10 22:39:46.701 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:39:46.744 [info] <0.463.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.463.0>
2016-04-10 22:39:46.758 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:47.478 [error] <0.521.0> gen_server <0.521.0> terminated with reason: killed
2016-04-10 22:39:47.480 [error] <0.986.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1006.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:47.478 [error] <0.521.0> CRASH REPORT Process <0.521.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:47.482 [error] <0.984.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.986.0> exit with reason shutdown in context child_terminated
2016-04-10 22:39:47.479 [error] <0.454.0> CRASH REPORT Process <0.454.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:47.482 [error] <0.984.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.986.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:47.483 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:39:47.526 [info] <0.1114.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1114.0>
2016-04-10 22:39:47.479 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:47.528 [info] <0.552.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.552.0>
2016-04-10 22:39:47.531 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:48.370 [error] <0.666.0> gen_server <0.666.0> terminated with reason: killed
2016-04-10 22:39:47.831 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:47.933 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:39:47.959 [info] <0.1227.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1227.0>
2016-04-10 22:39:48.370 [warning] <0.6.0> lager_error_logger_h dropped 21 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:48.371 [error] <0.1218.0> CRASH REPORT Process <0.1218.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:48.370 [error] <0.666.0> CRASH REPORT Process <0.666.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:48.371 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:48.371 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:48.422 [info] <0.1459.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1459.0>
2016-04-10 22:39:48.425 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:48.591 [error] <0.1450.0> CRASH REPORT Process <0.1450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:48.371 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:48.438 [info] <0.767.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.767.0>
2016-04-10 22:39:48.442 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:48.590 [error] <0.815.0> gen_server <0.815.0> terminated with reason: killed
2016-04-10 22:39:48.591 [error] <0.815.0> CRASH REPORT Process <0.815.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:48.591 [error] <0.758.0> CRASH REPORT Process <0.758.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:48.591 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:48.639 [info] <0.1573.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1573.0>
2016-04-10 22:39:48.845 [info] <0.1689.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1689.0>
2016-04-10 22:39:49.083 [warning] <0.6.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:49.083 [error] <0.1745.0> gen_server <0.1745.0> terminated with reason: killed
2016-04-10 22:39:49.083 [error] <0.1745.0> CRASH REPORT Process <0.1745.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:48.591 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:48.662 [info] <0.866.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.866.0>
2016-04-10 22:39:48.856 [info] <0.967.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.967.0>
2016-04-10 22:39:49.086 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:49.086 [error] <0.1021.0> gen_server <0.1021.0> terminated with reason: killed
2016-04-10 22:39:49.083 [error] <0.1680.0> CRASH REPORT Process <0.1680.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:49.086 [error] <0.1021.0> CRASH REPORT Process <0.1021.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:49.086 [error] <0.958.0> CRASH REPORT Process <0.958.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:49.087 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:49.139 [info] <0.1073.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1073.0>
2016-04-10 22:39:49.150 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:49.083 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:49.136 [info] <0.1815.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1815.0>
2016-04-10 22:39:49.442 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:49.600 [error] <0.1810.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1829.0> exit with reason killed in context child_terminated
2016-04-10 22:39:49.599 [error] <0.1126.0> gen_server <0.1126.0> terminated with reason: killed
2016-04-10 22:39:49.600 [error] <0.1810.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1829.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:49.599 [error] <0.1126.0> CRASH REPORT Process <0.1126.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:49.661 [info] <0.1947.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1947.0>
2016-04-10 22:39:49.665 [info] <0.1173.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1173.0>
2016-04-10 22:39:49.885 [info] <0.1274.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1274.0>
2016-04-10 22:39:50.450 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:50.450 [error] <0.1329.0> gen_server <0.1329.0> terminated with reason: killed
2016-04-10 22:39:49.871 [info] <0.2080.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2080.0>
2016-04-10 22:39:50.187 [warning] <0.6.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:50.188 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:50.452 [error] <0.2137.0> gen_server <0.2137.0> terminated with reason: killed
2016-04-10 22:39:50.450 [error] <0.1329.0> CRASH REPORT Process <0.1329.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:50.452 [error] <0.2137.0> CRASH REPORT Process <0.2137.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:50.454 [error] <0.2071.0> CRASH REPORT Process <0.2071.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:50.450 [error] <0.1265.0> CRASH REPORT Process <0.1265.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:50.451 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:50.499 [info] <0.1381.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1381.0>
2016-04-10 22:39:50.500 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:50.698 [error] <0.1435.0> gen_server <0.1435.0> terminated with reason: killed
2016-04-10 22:39:50.454 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:50.503 [info] <0.2221.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2221.0>
2016-04-10 22:39:50.698 [error] <0.1435.0> CRASH REPORT Process <0.1435.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:50.923 [info] <0.1470.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1470.0>
2016-04-10 22:39:51.075 [error] <0.1522.0> gen_server <0.1522.0> terminated with reason: killed
2016-04-10 22:39:50.921 [info] <0.2350.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2350.0>
2016-04-10 22:39:51.075 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:51.075 [error] <0.2347.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:39:51.075 [error] <0.2347.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:51.075 [error] <0.2343.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2345.0> exit with reason killed in context child_terminated
2016-04-10 22:39:51.075 [error] <0.2343.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2345.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:51.075 [error] <0.1522.0> CRASH REPORT Process <0.1522.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:51.075 [error] <0.2346.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:39:51.076 [error] <0.1461.0> CRASH REPORT Process <0.1461.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:51.075 [error] <0.2349.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:39:51.076 [error] <0.2349.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:51.076 [error] <0.2365.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:39:51.076 [error] <0.2365.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:51.079 [error] <0.2404.0> gen_server <0.2404.0> terminated with reason: killed
2016-04-10 22:39:51.079 [error] <0.2404.0> CRASH REPORT Process <0.2404.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:51.079 [error] <0.2341.0> CRASH REPORT Process <0.2341.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:51.076 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:51.131 [info] <0.1583.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1583.0>
2016-04-10 22:39:51.137 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:51.579 [error] <0.1638.0> gen_server <0.1638.0> terminated with reason: killed
2016-04-10 22:39:51.579 [error] <0.1638.0> CRASH REPORT Process <0.1638.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:39:51.656 [info] <0.1671.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1671.0>
2016-04-10 22:39:51.079 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:51.129 [info] <0.2482.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2482.0>
2016-04-10 22:39:51.652 [info] <0.2606.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2606.0>
2016-04-10 22:39:52.015 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:52.023 [info] <0.2734.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2734.0>
2016-04-10 22:39:52.025 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:52.060 [error] <0.2725.0> CRASH REPORT Process <0.2725.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:52.060 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:52.107 [info] <0.2828.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2828.0>
2016-04-10 22:39:53.335 [warning] <0.6.0> lager_error_logger_h dropped 35 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:53.343 [info] <0.2938.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2938.0>
2016-04-10 22:39:53.346 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:54.596 [error] <0.2929.0> CRASH REPORT Process <0.2929.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:54.596 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:56.677 [info] <0.3044.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3044.0>
2016-04-10 22:39:56.681 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:56.683 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:39:56.697 [info] <0.3092.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3092.0>
2016-04-10 22:39:56.704 [info] <0.3140.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3140.0>
2016-04-10 22:39:58.795 [info] <0.3212.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3212.0>
2016-04-10 22:39:58.797 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:39:58.811 [error] <0.3203.0> CRASH REPORT Process <0.3203.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:39:58.811 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:00.859 [info] <0.3295.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3295.0>
2016-04-10 22:40:00.862 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:00.866 [info] <0.3289.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 22:40:00.866 [info] <0.3289.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test9478@testing-worker-linux-docker-9239c715-3363-linux-12.2016-04-10_22.39.14/Mnesia2.test9478@testing-worker-linux-docker-9239c715-3363-linux-12/LATEST.LOG"] -> badarg

2016-04-10 22:40:00.867 [error] <0.3323.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3378.0>}})

2016-04-10 22:40:00.867 [error] <0.3326.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3378.0>}})

2016-04-10 22:40:00.868 [error] <0.3324.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3378.0>}})

2016-04-10 22:40:00.868 [error] <0.3322.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3378.0>}})

2016-04-10 22:40:00.868 [error] <0.3329.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3378.0>}})

2016-04-10 22:40:00.868 [error] <0.3330.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3378.0>}})

2016-04-10 22:40:00.868 [error] <0.3328.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}}} ({error,{already_started,<0.3378.0>}})

2016-04-10 22:40:00.868 [info] <0.3378.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): mnesia2_tm_25 terminated: shutdown

2016-04-10 22:40:02.965 [warning] <0.6.0> lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:40:02.967 [info] <0.3416.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3416.0>
2016-04-10 22:40:02.971 [info] <0.3410.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): mnesia2_monitor starting: <0.3412.0>

2016-04-10 22:40:02.971 [info] <0.3410.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Mnesia2 debug level set to verbose
2016-04-10 22:40:02.971 [info] <0.3410.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): mnesia2_subscr starting: <0.3413.0>

2016-04-10 22:40:02.971 [info] <0.3410.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): mnesia2_locker starting: <0.3414.0>

2016-04-10 22:40:02.972 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:02.972 [error] <0.3424.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3455.0>}})

2016-04-10 22:40:02.972 [error] <0.3426.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3455.0>}})

2016-04-10 22:40:04.992 [warning] <0.6.0> lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:40:04.993 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): mnesia2_monitor starting: <0.3493.0>

2016-04-10 22:40:04.993 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Version: "1.0.0"

2016-04-10 22:40:04.994 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env access_module: mnesia2

2016-04-10 22:40:04.995 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env auto_repair: true

2016-04-10 22:40:04.995 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env backup_module: mnesia2_backup

2016-04-10 22:40:04.995 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env debug: debug

2016-04-10 22:40:04.995 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test9478@testing-worker-linux-docker-9239c715-3363-linux-12.2016-04-10_22.39.14/Mnesia2.test9478@testing-worker-linux-docker-9239c715-3363-linux-12"

2016-04-10 22:40:04.996 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_disc_copies_at_startup: true

2016-04-10 22:40:04.996 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_log_load_regulation: false

2016-04-10 22:40:04.996 [info] <0.3497.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3497.0>
2016-04-10 22:40:04.996 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_log_time_threshold: 180000

2016-04-10 22:40:04.997 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_log_update_in_place: true

2016-04-10 22:40:04.997 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_log_write_threshold: 1000

2016-04-10 22:40:04.997 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env event_module: mnesia2_event

2016-04-10 22:40:04.998 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env extra_db_nodes: []

2016-04-10 22:40:04.999 [info] <0.3491.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env ignore_fallback_at_startup: false

2016-04-10 22:40:05.000 [warning] <0.6.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:40:05.000 [error] <0.3533.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_31,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_31,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.000 [error] <0.3532.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_30,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_30,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.000 [info] <0.3536.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): mnesia2_tm_16 terminated: shutdown

2016-04-10 22:40:05.001 [error] <0.3528.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_26,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_26,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.001 [error] <0.3524.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_22,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_22,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.001 [error] <0.3508.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.001 [error] <0.3503.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.001 [error] <0.3505.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.001 [error] <0.3507.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.001 [error] <0.3506.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.001 [error] <0.3504.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.001 [error] <0.3509.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.002 [error] <0.3511.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.002 [error] <0.3510.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.002 [error] <0.3513.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.002 [error] <0.3515.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.002 [error] <0.3514.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.002 [error] <0.3512.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}}} ({error,{already_started,<0.3536.0>}})

2016-04-10 22:40:05.002 [error] <0.3488.0> CRASH REPORT Process <0.3488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:40:05.002 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:07.022 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): mnesia2_monitor starting: <0.3560.0>

2016-04-10 22:40:07.023 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Version: "1.0.0"

2016-04-10 22:40:07.023 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env access_module: mnesia2

2016-04-10 22:40:07.024 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env auto_repair: true

2016-04-10 22:40:07.024 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env backup_module: mnesia2_backup

2016-04-10 22:40:07.024 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env debug: trace

2016-04-10 22:40:07.025 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test9478@testing-worker-linux-docker-9239c715-3363-linux-12.2016-04-10_22.39.14/Mnesia2.test9478@testing-worker-linux-docker-9239c715-3363-linux-12"

2016-04-10 22:40:07.025 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_disc_copies_at_startup: true

2016-04-10 22:40:07.025 [info] <0.3564.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3564.0>
2016-04-10 22:40:07.026 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_log_load_regulation: false

2016-04-10 22:40:07.026 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_log_time_threshold: 180000

2016-04-10 22:40:07.026 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_log_update_in_place: true

2016-04-10 22:40:07.027 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_log_write_threshold: 1000

2016-04-10 22:40:07.027 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env event_module: mnesia2_event

2016-04-10 22:40:07.027 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env extra_db_nodes: []

2016-04-10 22:40:07.028 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env ignore_fallback_at_startup: false

2016-04-10 22:40:07.028 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:40:07.028 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env max_wait_for_decision: infinity

2016-04-10 22:40:07.029 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env schema_location: opt_disc

2016-04-10 22:40:07.029 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:07.029 [info] <0.3558.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env core_dir: false

2016-04-10 22:40:07.030 [info] <0.3610.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): mnesia2_tm_13 terminated: shutdown

2016-04-10 22:40:07.030 [error] <0.3574.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3610.0>}})

2016-04-10 22:40:07.031 [error] <0.3573.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3610.0>}})

2016-04-10 22:40:07.031 [error] <0.3571.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3610.0>}})

2016-04-10 22:40:07.031 [error] <0.3576.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3610.0>}})

2016-04-10 22:40:07.031 [error] <0.3578.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3610.0>}})

2016-04-10 22:40:07.031 [error] <0.3577.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3610.0>}})

2016-04-10 22:40:07.031 [error] <0.3580.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3610.0>}})

2016-04-10 22:40:07.031 [error] <0.3555.0> CRASH REPORT Process <0.3555.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:40:07.031 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:09.052 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): mnesia2_monitor starting: <0.3617.0>

2016-04-10 22:40:09.054 [info] <0.3621.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3621.0>
2016-04-10 22:40:09.055 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Version: "1.0.0"

2016-04-10 22:40:09.055 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env access_module: mnesia2

2016-04-10 22:40:09.055 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env auto_repair: true

2016-04-10 22:40:09.055 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env backup_module: mnesia2_backup

2016-04-10 22:40:09.055 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env debug: debug

2016-04-10 22:40:09.055 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test9478@testing-worker-linux-docker-9239c715-3363-linux-12.2016-04-10_22.39.14/Mnesia2.test9478@testing-worker-linux-docker-9239c715-3363-linux-12"

2016-04-10 22:40:09.056 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_disc_copies_at_startup: true

2016-04-10 22:40:09.056 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_log_load_regulation: false

2016-04-10 22:40:09.058 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_log_time_threshold: 180000

2016-04-10 22:40:09.058 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_log_update_in_place: true

2016-04-10 22:40:09.059 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env dump_log_write_threshold: 1000

2016-04-10 22:40:09.059 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env event_module: mnesia2_event

2016-04-10 22:40:09.059 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env extra_db_nodes: []

2016-04-10 22:40:09.060 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env ignore_fallback_at_startup: false

2016-04-10 22:40:09.060 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:40:09.060 [info] <0.3615.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): Env max_wait_for_decision: infinity

2016-04-10 22:40:11.085 [info] <0.3670.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3670.0>
2016-04-10 22:40:11.088 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:40:11.088 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:11.089 [error] <0.3661.0> CRASH REPORT Process <0.3661.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:40:11.089 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:13.176 [info] <0.3734.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3734.0>
2016-04-10 22:40:13.180 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:13.181 [error] <0.3725.0> CRASH REPORT Process <0.3725.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:40:13.181 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:14.282 [info] <0.3805.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3805.0>
2016-04-10 22:40:14.284 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:14.287 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:40:14.294 [info] <0.3866.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3866.0>
2016-04-10 22:40:21.600 [error] <0.3860.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:22.545 [error] <0.3860.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:29.077 [error] <0.3860.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:29.248 [error] <0.3860.0> Mnesia2('test9478@testing-worker-linux-docker-9239c715-3363-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:29.337 [error] <0.3857.0> CRASH REPORT Process <0.3857.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:40:29.337 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:31.456 [info] <0.4396.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4396.0>
2016-04-10 22:40:31.459 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:37.465 [error] <0.4387.0> CRASH REPORT Process <0.4387.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:40:37.465 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:39.556 [info] <0.4496.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4496.0>
2016-04-10 22:40:39.559 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:40.577 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:40:43.215 [info] <0.4612.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4612.0>
2016-04-10 22:40:43.217 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:43.224 [error] <0.4603.0> CRASH REPORT Process <0.4603.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:40:43.224 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:45.273 [info] <0.4679.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4679.0>
2016-04-10 22:40:45.275 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:45.298 [error] <0.4670.0> CRASH REPORT Process <0.4670.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:40:45.298 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:47.415 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:40:47.429 [info] <0.1798.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1798.0>
2016-04-10 22:40:47.433 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:47.422 [info] <0.4771.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4771.0>
2016-04-10 22:40:47.424 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:48.435 [error] <0.1850.0> gen_server <0.1850.0> terminated with reason: killed
2016-04-10 22:40:48.435 [error] <0.1850.0> CRASH REPORT Process <0.1850.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:40:48.435 [error] <0.1789.0> CRASH REPORT Process <0.1789.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:40:48.435 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:50.470 [info] <0.1866.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1866.0>
2016-04-10 22:40:50.474 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:51.477 [error] <0.4834.0> gen_server <0.4834.0> terminated with reason: killed
2016-04-10 22:40:51.477 [error] <0.4834.0> CRASH REPORT Process <0.4834.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:40:51.478 [error] <0.4762.0> CRASH REPORT Process <0.4762.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:40:51.478 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:52.537 [error] <0.1861.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1879.0> exit with reason killed in context child_terminated
2016-04-10 22:40:52.537 [error] <0.1861.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1879.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:40:52.537 [error] <0.1857.0> CRASH REPORT Process <0.1857.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:40:52.537 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:53.611 [info] <0.4877.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4877.0>
2016-04-10 22:40:53.613 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:53.643 [error] <0.4931.0> gen_server <0.4931.0> terminated with reason: killed
2016-04-10 22:40:53.615 [info] <0.1947.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1947.0>
2016-04-10 22:40:53.642 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:53.643 [error] <0.1999.0> gen_server <0.1999.0> terminated with reason: killed
2016-04-10 22:40:53.643 [error] <0.4931.0> CRASH REPORT Process <0.4931.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:40:53.643 [error] <0.1999.0> CRASH REPORT Process <0.1999.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:40:53.645 [error] <0.4868.0> CRASH REPORT Process <0.4868.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:40:53.644 [error] <0.1938.0> CRASH REPORT Process <0.1938.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:40:53.646 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:53.687 [info] <0.4957.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4957.0>
2016-04-10 22:40:53.644 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:57.582 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:40:57.654 [info] <0.5081.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.5081.0>
2016-04-10 22:40:57.658 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:40:57.646 [info] <0.2022.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2022.0>
2016-04-10 22:40:57.647 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:06.599 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:06.602 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:07.741 [info] <0.2144.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2144.0>
2016-04-10 22:41:07.744 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:08.064 [error] <0.2199.0> gen_server <0.2199.0> terminated with reason: killed
2016-04-10 22:41:08.064 [error] <0.2199.0> CRASH REPORT Process <0.2199.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:08.064 [error] <0.2135.0> CRASH REPORT Process <0.2135.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:07.723 [info] <0.5212.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.5212.0>
2016-04-10 22:41:08.027 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:08.086 [error] <0.5203.0> CRASH REPORT Process <0.5203.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:08.086 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:08.116 [info] <0.5301.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.5301.0>
2016-04-10 22:41:08.120 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:08.645 [error] <0.5372.0> gen_server <0.5372.0> terminated with reason: killed
2016-04-10 22:41:08.645 [error] <0.5372.0> CRASH REPORT Process <0.5372.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:08.645 [error] <0.5292.0> CRASH REPORT Process <0.5292.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:08.645 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:08.064 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:08.297 [info] <0.2233.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2233.0>
2016-04-10 22:41:08.310 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:09.753 [error] <0.2228.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2252.0> exit with reason killed in context child_terminated
2016-04-10 22:41:09.753 [error] <0.2228.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2252.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:09.754 [error] <0.2224.0> CRASH REPORT Process <0.2224.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:09.754 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:10.836 [info] <0.2336.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2336.0>
2016-04-10 22:41:10.842 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:10.853 [error] <0.2348.0> gen_server <0.2348.0> terminated with reason: killed
2016-04-10 22:41:10.830 [info] <0.5424.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.5424.0>
2016-04-10 22:41:10.832 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:10.853 [error] <0.5488.0> gen_server <0.5488.0> terminated with reason: killed
2016-04-10 22:41:10.853 [error] <0.5488.0> CRASH REPORT Process <0.5488.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:10.853 [error] <0.2348.0> CRASH REPORT Process <0.2348.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:10.853 [error] <0.5415.0> CRASH REPORT Process <0.5415.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:10.853 [error] <0.2327.0> CRASH REPORT Process <0.2327.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:10.853 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:10.853 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:12.973 [info] <0.2411.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2411.0>
2016-04-10 22:41:12.978 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:12.979 [error] <0.2406.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.2415.0> exit with reason killed in context child_terminated
2016-04-10 22:41:12.966 [info] <0.5535.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.5535.0>
2016-04-10 22:41:12.968 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:12.981 [error] <0.5599.0> gen_server <0.5599.0> terminated with reason: killed
2016-04-10 22:41:12.979 [error] <0.2406.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.2415.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:12.981 [error] <0.5599.0> CRASH REPORT Process <0.5599.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:12.982 [error] <0.5526.0> CRASH REPORT Process <0.5526.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:12.980 [error] <0.2423.0> gen_server <0.2423.0> terminated with reason: killed
2016-04-10 22:41:12.980 [error] <0.2423.0> CRASH REPORT Process <0.2423.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:12.980 [error] <0.2402.0> CRASH REPORT Process <0.2402.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:12.982 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:12.980 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:15.345 [info] <0.5615.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.5615.0>
2016-04-10 22:41:15.370 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:15.384 [error] <0.5676.0> gen_server <0.5676.0> terminated with reason: killed
2016-04-10 22:41:15.384 [error] <0.5676.0> CRASH REPORT Process <0.5676.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:15.384 [error] <0.5606.0> CRASH REPORT Process <0.5606.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:15.007 [info] <0.2470.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2470.0>
2016-04-10 22:41:15.008 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:15.384 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:16.777 [error] <0.2461.0> CRASH REPORT Process <0.2461.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:16.777 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:17.873 [info] <0.2559.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2559.0>
2016-04-10 22:41:17.891 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:18.200 [error] <0.2572.0> gen_server <0.2572.0> terminated with reason: killed
2016-04-10 22:41:18.115 [info] <0.7.0> Application lager started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:18.115 [info] <0.7.0> Application poolgirl started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:18.138 [info] <0.101.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.101.0>
2016-04-10 22:41:18.153 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:18.200 [error] <0.96.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.103.0> exit with reason killed in context child_terminated
2016-04-10 22:41:17.868 [info] <0.5740.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.5740.0>
2016-04-10 22:41:17.870 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:18.202 [error] <0.5793.0> gen_server <0.5793.0> terminated with reason: killed
2016-04-10 22:41:18.200 [error] <0.96.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.103.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:18.202 [error] <0.5793.0> CRASH REPORT Process <0.5793.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:18.201 [error] <0.94.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.96.0> exit with reason shutdown in context child_terminated
2016-04-10 22:41:18.200 [error] <0.2572.0> CRASH REPORT Process <0.2572.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:18.202 [error] <0.5785.0> gen_server <0.5785.0> terminated with reason: killed
2016-04-10 22:41:18.201 [error] <0.94.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.96.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:18.201 [error] <0.2610.0> gen_server <0.2610.0> terminated with reason: killed
2016-04-10 22:41:18.202 [error] <0.5785.0> CRASH REPORT Process <0.5785.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:18.201 [error] <0.2610.0> CRASH REPORT Process <0.2610.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:18.204 [error] <0.5731.0> CRASH REPORT Process <0.5731.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:18.201 [error] <0.2550.0> CRASH REPORT Process <0.2550.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:18.204 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:18.201 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:18.202 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:41:20.318 [info] <0.5835.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.5835.0>
2016-04-10 22:41:20.320 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:20.345 [error] <0.5830.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5846.0> exit with reason killed in context child_terminated
2016-04-10 22:41:20.325 [info] <0.2640.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2640.0>
2016-04-10 22:41:20.331 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:20.346 [error] <0.2631.0> CRASH REPORT Process <0.2631.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:20.345 [error] <0.5830.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5846.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:20.347 [error] <0.5899.0> gen_server <0.5899.0> terminated with reason: killed
2016-04-10 22:41:20.347 [error] <0.5899.0> CRASH REPORT Process <0.5899.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:20.347 [error] <0.5826.0> CRASH REPORT Process <0.5826.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:20.347 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:20.346 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:22.432 [info] <0.5929.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.5929.0>
2016-04-10 22:41:22.434 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:22.459 [error] <0.5973.0> gen_server <0.5973.0> terminated with reason: killed
2016-04-10 22:41:22.437 [info] <0.2710.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2710.0>
2016-04-10 22:41:22.440 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:22.460 [error] <0.2722.0> gen_server <0.2722.0> terminated with reason: killed
2016-04-10 22:41:22.459 [error] <0.5973.0> CRASH REPORT Process <0.5973.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:22.460 [error] <0.2722.0> CRASH REPORT Process <0.2722.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:22.461 [error] <0.5920.0> CRASH REPORT Process <0.5920.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:22.460 [error] <0.2701.0> CRASH REPORT Process <0.2701.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:22.461 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:22.460 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:24.610 [info] <0.2785.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2785.0>
2016-04-10 22:41:24.614 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:24.712 [error] <0.2780.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.2800.0> exit with reason killed in context child_terminated
2016-04-10 22:41:24.712 [error] <0.2780.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.2800.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:24.712 [error] <0.2780.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2798.0> exit with reason killed in context shutdown_error
2016-04-10 22:41:24.713 [error] <0.2839.0> gen_server <0.2839.0> terminated with reason: killed
2016-04-10 22:41:24.713 [error] <0.2839.0> CRASH REPORT Process <0.2839.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:24.713 [error] <0.2776.0> CRASH REPORT Process <0.2776.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:24.604 [info] <0.6015.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.6015.0>
2016-04-10 22:41:24.606 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:24.713 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:25.742 [error] <0.6006.0> CRASH REPORT Process <0.6006.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:25.742 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:27.773 [info] <0.2855.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2855.0>
2016-04-10 22:41:27.775 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:32.810 [info] <0.6093.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.6093.0>
2016-04-10 22:41:32.831 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:32.835 [error] <0.6088.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.6113.0> exit with reason killed in context child_terminated
2016-04-10 22:41:32.836 [error] <0.2922.0> gen_server <0.2922.0> terminated with reason: killed
2016-04-10 22:41:32.835 [error] <0.6088.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.6113.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:32.836 [error] <0.2922.0> CRASH REPORT Process <0.2922.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:32.837 [error] <0.6146.0> gen_server <0.6146.0> terminated with reason: killed
2016-04-10 22:41:32.837 [error] <0.6146.0> CRASH REPORT Process <0.6146.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:32.837 [error] <0.2846.0> CRASH REPORT Process <0.2846.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:32.838 [error] <0.6084.0> CRASH REPORT Process <0.6084.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:32.838 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:32.837 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:34.023 [info] <0.2954.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2954.0>
2016-04-10 22:41:34.036 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:34.094 [error] <0.3002.0> gen_server <0.3002.0> terminated with reason: killed
2016-04-10 22:41:34.094 [error] <0.3002.0> CRASH REPORT Process <0.3002.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:34.095 [error] <0.2945.0> CRASH REPORT Process <0.2945.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:34.012 [info] <0.6203.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.6203.0>
2016-04-10 22:41:34.015 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:34.160 [error] <0.6198.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6215.0> exit with reason killed in context child_terminated
2016-04-10 22:41:34.161 [error] <0.6198.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6215.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:34.161 [error] <0.6306.0> gen_server <0.6306.0> terminated with reason: killed
2016-04-10 22:41:34.161 [error] <0.6306.0> CRASH REPORT Process <0.6306.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:34.162 [error] <0.6290.0> gen_server <0.6290.0> terminated with reason: killed
2016-04-10 22:41:34.162 [error] <0.6290.0> CRASH REPORT Process <0.6290.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:34.162 [error] <0.6267.0> gen_server <0.6267.0> terminated with reason: killed
2016-04-10 22:41:34.162 [error] <0.6267.0> CRASH REPORT Process <0.6267.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:34.163 [error] <0.6194.0> CRASH REPORT Process <0.6194.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:34.056 [info] <0.191.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.191.0>
2016-04-10 22:41:34.061 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:34.183 [error] <0.182.0> CRASH REPORT Process <0.182.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:34.163 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:34.277 [info] <0.6325.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.6325.0>
2016-04-10 22:41:34.095 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:34.121 [info] <0.3045.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3045.0>
2016-04-10 22:41:34.217 [info] <0.3140.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3140.0>
2016-04-10 22:41:34.183 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:34.281 [info] <0.296.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.296.0>
2016-04-10 22:41:34.293 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:35.111 [error] <0.367.0> gen_server <0.367.0> terminated with reason: killed
2016-04-10 22:41:35.111 [error] <0.367.0> CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:35.112 [error] <0.356.0> gen_server <0.356.0> terminated with reason: killed
2016-04-10 22:41:35.112 [error] <0.356.0> CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:35.112 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:35.112 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:35.138 [info] <0.391.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.391.0>
2016-04-10 22:41:35.139 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:37.187 [warning] <0.6.0> lager_error_logger_h dropped 23 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:37.187 [error] <0.6425.0> gen_server <0.6425.0> terminated with reason: killed
2016-04-10 22:41:37.188 [error] <0.6425.0> CRASH REPORT Process <0.6425.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:37.188 [error] <0.6395.0> gen_server <0.6395.0> terminated with reason: killed
2016-04-10 22:41:37.188 [error] <0.6395.0> CRASH REPORT Process <0.6395.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:37.211 [warning] <0.6.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:37.211 [error] <0.3233.0> gen_server <0.3233.0> terminated with reason: killed
2016-04-10 22:41:37.188 [error] <0.6316.0> CRASH REPORT Process <0.6316.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:37.211 [error] <0.3233.0> CRASH REPORT Process <0.3233.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:37.212 [error] <0.3131.0> CRASH REPORT Process <0.3131.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:37.236 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:37.255 [info] <0.497.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.497.0>
2016-04-10 22:41:37.256 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:38.097 [error] <0.563.0> gen_server <0.563.0> terminated with reason: killed
2016-04-10 22:41:38.097 [error] <0.563.0> CRASH REPORT Process <0.563.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:38.097 [error] <0.573.0> gen_server <0.573.0> terminated with reason: killed
2016-04-10 22:41:38.097 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:38.098 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:37.188 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:37.290 [info] <0.6442.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.6442.0>
2016-04-10 22:41:37.301 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:38.196 [error] <0.6536.0> gen_server <0.6536.0> terminated with reason: killed
2016-04-10 22:41:38.196 [error] <0.6536.0> CRASH REPORT Process <0.6536.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:38.196 [error] <0.6531.0> gen_server <0.6531.0> terminated with reason: killed
2016-04-10 22:41:38.196 [error] <0.6531.0> CRASH REPORT Process <0.6531.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:38.196 [error] <0.6515.0> gen_server <0.6515.0> terminated with reason: killed
2016-04-10 22:41:38.196 [error] <0.6515.0> CRASH REPORT Process <0.6515.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:38.196 [error] <0.6433.0> CRASH REPORT Process <0.6433.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:37.212 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:37.272 [info] <0.3254.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3254.0>
2016-04-10 22:41:37.591 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:38.217 [error] <0.3344.0> gen_server <0.3344.0> terminated with reason: killed
2016-04-10 22:41:38.098 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:38.123 [info] <0.595.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.595.0>
2016-04-10 22:41:38.124 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:38.217 [error] <0.3344.0> CRASH REPORT Process <0.3344.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:38.218 [error] <0.3245.0> CRASH REPORT Process <0.3245.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:38.218 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:38.277 [info] <0.3365.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3365.0>
2016-04-10 22:41:38.289 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:39.109 [error] <0.3437.0> gen_server <0.3437.0> terminated with reason: killed
2016-04-10 22:41:39.109 [error] <0.3437.0> CRASH REPORT Process <0.3437.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:39.109 [error] <0.3426.0> gen_server <0.3426.0> terminated with reason: killed
2016-04-10 22:41:39.109 [error] <0.3426.0> CRASH REPORT Process <0.3426.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:39.110 [error] <0.3356.0> CRASH REPORT Process <0.3356.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:39.110 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:39.163 [info] <0.3461.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3461.0>
2016-04-10 22:41:39.174 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:39.187 [error] <0.3489.0> gen_server <0.3489.0> terminated with reason: killed
2016-04-10 22:41:39.187 [error] <0.3489.0> CRASH REPORT Process <0.3489.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:39.188 [error] <0.3519.0> gen_server <0.3519.0> terminated with reason: killed
2016-04-10 22:41:39.188 [error] <0.3519.0> CRASH REPORT Process <0.3519.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:38.196 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:38.273 [info] <0.6553.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.6553.0>
2016-04-10 22:41:38.243 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:38.254 [info] <0.696.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.696.0>
2016-04-10 22:41:40.209 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:40.212 [info] <0.3539.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3539.0>
2016-04-10 22:41:40.223 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:40.276 [error] <0.3587.0> gen_server <0.3587.0> terminated with reason: killed
2016-04-10 22:41:40.279 [error] <0.6666.0> gen_server <0.6666.0> terminated with reason: killed
2016-04-10 22:41:40.276 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:40.276 [error] <0.770.0> gen_server <0.770.0> terminated with reason: killed
2016-04-10 22:41:40.276 [error] <0.3587.0> CRASH REPORT Process <0.3587.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:40.276 [error] <0.770.0> CRASH REPORT Process <0.770.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:40.277 [error] <0.687.0> CRASH REPORT Process <0.687.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:40.279 [error] <0.6666.0> CRASH REPORT Process <0.6666.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:40.279 [error] <0.6617.0> gen_server <0.6617.0> terminated with reason: killed
2016-04-10 22:41:40.276 [error] <0.3553.0> gen_server <0.3553.0> terminated with reason: killed
2016-04-10 22:41:40.280 [error] <0.6617.0> CRASH REPORT Process <0.6617.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:40.277 [error] <0.3553.0> CRASH REPORT Process <0.3553.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:40.277 [error] <0.3530.0> CRASH REPORT Process <0.3530.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:40.280 [error] <0.6544.0> CRASH REPORT Process <0.6544.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:40.277 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:40.336 [info] <0.3617.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3617.0>
2016-04-10 22:41:40.703 [info] <0.3713.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3713.0>
2016-04-10 22:41:40.771 [info] <0.3803.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3803.0>
2016-04-10 22:41:40.831 [info] <0.3903.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3903.0>
2016-04-10 22:41:40.277 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:40.280 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:40.334 [info] <0.6699.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.6699.0>
2016-04-10 22:41:40.638 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:41.429 [warning] <0.6.0> lager_error_logger_h dropped 41 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:41.429 [error] <0.3958.0> gen_server <0.3958.0> terminated with reason: killed
2016-04-10 22:41:41.430 [error] <0.3958.0> CRASH REPORT Process <0.3958.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:41.430 [error] <0.3894.0> CRASH REPORT Process <0.3894.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:41.430 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:41.977 [info] <0.3985.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.3985.0>
2016-04-10 22:41:41.991 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:42.045 [error] <0.4032.0> gen_server <0.4032.0> terminated with reason: killed
2016-04-10 22:41:41.356 [info] <0.6813.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.6813.0>
2016-04-10 22:41:41.379 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:41.428 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:41.472 [info] <0.6896.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.6896.0>
2016-04-10 22:41:42.046 [error] <0.6887.0> CRASH REPORT Process <0.6887.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:42.045 [error] <0.4032.0> CRASH REPORT Process <0.4032.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:42.046 [error] <0.3976.0> CRASH REPORT Process <0.3976.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:42.046 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:42.133 [info] <0.6997.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.6997.0>
2016-04-10 22:41:42.138 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:42.046 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:42.137 [info] <0.4077.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4077.0>
2016-04-10 22:41:42.526 [error] <0.6988.0> CRASH REPORT Process <0.6988.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:42.441 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:42.525 [error] <0.4141.0> gen_server <0.4141.0> terminated with reason: killed
2016-04-10 22:41:42.525 [error] <0.4141.0> CRASH REPORT Process <0.4141.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:42.140 [info] <0.847.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.847.0>
2016-04-10 22:41:42.146 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:42.535 [error] <0.902.0> gen_server <0.902.0> terminated with reason: killed
2016-04-10 22:41:42.525 [error] <0.4134.0> gen_server <0.4134.0> terminated with reason: killed
2016-04-10 22:41:42.525 [error] <0.4134.0> CRASH REPORT Process <0.4134.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:42.535 [error] <0.907.0> gen_server <0.907.0> terminated with reason: killed
2016-04-10 22:41:42.535 [error] <0.902.0> CRASH REPORT Process <0.902.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:42.535 [error] <0.907.0> CRASH REPORT Process <0.907.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:42.535 [error] <0.838.0> CRASH REPORT Process <0.838.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:42.535 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:42.566 [info] <0.950.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.950.0>
2016-04-10 22:41:42.568 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:42.625 [error] <0.945.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.951.0> exit with reason killed in context child_terminated
2016-04-10 22:41:42.626 [error] <0.945.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.951.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:42.649 [info] <0.1027.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1027.0>
2016-04-10 22:41:42.570 [info] <0.4171.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4171.0>
2016-04-10 22:41:42.651 [info] <0.4249.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4249.0>
2016-04-10 22:41:42.526 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:42.594 [info] <0.7108.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.7108.0>
2016-04-10 22:41:42.681 [info] <0.7200.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.7200.0>
2016-04-10 22:41:52.703 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:52.703 [error] <0.7193.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 22:41:52.703 [error] <0.7196.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:41:52.703 [error] <0.7199.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:41:52.703 [error] <0.7199.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:52.703 [error] <0.7219.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:41:52.703 [error] <0.7219.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:52.703 [error] <0.7197.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:41:52.703 [error] <0.7197.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:52.704 [error] <0.7191.0> CRASH REPORT Process <0.7191.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-10 22:41:52.704 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 22:41:52.704 [error] <0.7196.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:52.795 [warning] <0.6.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:52.796 [error] <0.1076.0> gen_server <0.1076.0> terminated with reason: killed
2016-04-10 22:41:52.796 [error] <0.1076.0> CRASH REPORT Process <0.1076.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:52.796 [error] <0.1071.0> gen_server <0.1071.0> terminated with reason: killed
2016-04-10 22:41:52.796 [error] <0.1071.0> CRASH REPORT Process <0.1071.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:41:52.796 [error] <0.1018.0> CRASH REPORT Process <0.1018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:41:52.796 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:52.796 [error] <0.4244.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.4253.0> exit with reason killed in context child_terminated
2016-04-10 22:41:52.796 [error] <0.4244.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.4253.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:52.797 [error] <0.4244.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4251.0> exit with reason killed in context shutdown_error
2016-04-10 22:41:52.797 [error] <0.4242.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.4244.0> exit with reason shutdown in context child_terminated
2016-04-10 22:41:52.797 [error] <0.4242.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.4244.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:52.796 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:52.798 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:41:55.291 [info] <0.7309.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.7309.0>
2016-04-10 22:41:55.293 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:59.218 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:59.351 [info] <0.7445.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.7445.0>
2016-04-10 22:41:59.657 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:59.354 [info] <0.4340.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4340.0>
2016-04-10 22:41:59.386 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:41:59.365 [info] <0.1123.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1123.0>
2016-04-10 22:41:59.382 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:05.735 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:05.891 [info] <0.1238.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1238.0>
2016-04-10 22:42:05.900 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:05.736 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:05.868 [info] <0.7575.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.7575.0>
2016-04-10 22:42:05.871 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:05.767 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:05.889 [info] <0.4455.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4455.0>
2016-04-10 22:42:06.195 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:12.319 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:12.453 [info] <0.1352.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.1352.0>
2016-04-10 22:42:12.469 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:12.319 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:12.444 [info] <0.7704.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.7704.0>
2016-04-10 22:42:12.446 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:12.325 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:12.452 [info] <0.4572.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4572.0>
2016-04-10 22:42:12.756 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:28.621 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:28.799 [info] <0.2477.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2477.0>
2016-04-10 22:42:28.820 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:28.648 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:28.798 [info] <0.5698.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.5698.0>
2016-04-10 22:42:29.102 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:28.653 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:28.788 [info] <0.8842.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.8842.0>
2016-04-10 22:42:28.790 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:35.437 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:35.559 [info] <0.8980.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.8980.0>
2016-04-10 22:42:35.561 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:35.442 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:35.575 [info] <0.5825.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.5825.0>
2016-04-10 22:42:35.589 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:35.440 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:35.575 [info] <0.2600.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.2600.0>
2016-04-10 22:42:35.590 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:41.866 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:41.989 [info] <0.10460.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.10460.0>
2016-04-10 22:42:42.293 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:41.867 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:42.009 [info] <0.4069.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.4069.0>
2016-04-10 22:42:42.013 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:41.877 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:41.992 [info] <0.7296.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.7296.0>
2016-04-10 22:42:42.296 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:48.573 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:48.693 [info] <0.8356.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.8356.0>
2016-04-10 22:42:48.740 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:48.574 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:48.691 [info] <0.10894.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.10894.0>
2016-04-10 22:42:48.996 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:48.579 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:48.697 [info] <0.6090.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.6090.0>
2016-04-10 22:42:48.715 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:55.133 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:55.294 [info] <0.11025.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12', <0.11025.0>
2016-04-10 22:42:55.307 [info] <0.7.0> Application mnesia2 started on node 'test9478@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:55.132 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:55.289 [info] <0.6202.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12', <0.6202.0>
2016-04-10 22:42:55.593 [info] <0.7.0> Application mnesia2 started on node 'd719806o719798n719801@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:42:55.169 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:55.291 [info] <0.9152.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12', <0.9152.0>
2016-04-10 22:42:55.597 [info] <0.7.0> Application mnesia2 started on node 'd719803o719793n719795@testing-worker-linux-docker-9239c715-3363-linux-12'
2016-04-10 22:43:01.830 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:01.836 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:01.833 [info] <0.7.0> Application mnesia2 exited with reason: stopped
